Add friends likes
KirillSenchenkov/java-filmorate pull request #2
Opened 2023-06-22 20:16 UTC by KirillSenchenkov

2023-06-23 05:06 UTC, sergeymamonov requested changes
Класс Validator, используется ли где-то поле userId?
ValidationException наследник необрабатываемого исключения, поэтому не обязательно писать  throws ValidationException в определении методов.
ValidatorTest, поле startDate оформлено как константа по модификаторам, но написание не как полагается у констант.

В тестах лучше формировать тестовые данные так, чтобы они говорили сами за себя. Сравните sunbaked и not_valid_email, Maikoo Heikoo и name with space
Параметризированный тест - это тест, в который мы передаем несколько разных тестовых значений одного аргумента. Если значение одно, то не нужно делать тест параметризированным. Можно указать это значение в тесте.

2023-06-23 05:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmStorage filmStorage, FilmService filmService) {
Не обязательно писать конструктор руками, если можно воспользоваться аннотацией Lombok @AllArgsConstructor? Аналогично и для других классов, где можно воспользоваться этой аннотацией

2023-06-23 05:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +}
Еще можно добавить обработку рантайм ошибки (500 статус код).

2023-06-23 05:06 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/validator/ValidatorTest.java
> +    private static final UserStorage userStorage = new InMemoryUserStorage();
Поля userStorage и другие не нужно делать статическими.

2023-06-25 12:21 UTC, KirillSenchenkov commented
> 
Не до конца понял про параметризированный тест: у меня задан в нем одно значение и далее я прогоняю их по пустому и нулевому значению, я могу это сделать не указывая что тест параметризированный ? в статье которой пользовался не увидел как это сделать, ведь я передаю в метод аргумент. и если я его задам в теле метода я же не смогу запустить нулевой и пустой аргумент.

2023-06-26 04:25 UTC, sergeymamonov commented
> ValidatorTest

Да, не заметил, что еще на аннотацию @NullAndEmptySource. Так что это замечание не учитывать.

2023-06-26 04:26 UTC, sergeymamonov approved these changes

2023-06-26 04:26 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +}
Еще можно добавить обработку ошибки невалидный запрос (400 статус код).

2023-06-26 14:45 UTC, merged