Add database
KirillSenchenkov/java-filmorate pull request #3
Opened 2023-07-10 21:34 UTC by KirillSenchenkov

2023-07-12 04:08 UTC, sergeymamonov requested changes
В ErrorHandler можно еще добавить обработку ошибки, связанную с невалидными данными (400 статус код).

А HttpStatus.NOT_FOUND - это когда мы получили валидные данные от пользователя, но по результатам поиска ничего не нашлось.

С этого спринта уже можно удалить классы хранения, работающие в оперативной памяти.

В классе Validator startDate - это константа, поэтому ее название нужно писать заглавными буквами.
В классе Validatior число 200 нужно вынести из кода и оформить как константу.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    private final GenreDbStorage genreDbStorage;
Из контроллера мы должны обращаться к сервису. Поэтому из всех контроллеров необходимо удалить классы ...Storage.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        return genreDbStorage.getAllGenre();
Здесь необходимо вызывать соответствующий метод сервиса.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DbFilmService.java
> +                        .queryForObject("SELECT COUNT(*) FROM film_like WHERE film_id = ? AND user_id = ?",
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DbFilmService.java
> +                    jdbcTemplate.update("INSERT INTO film_like (film_id, user_id) VALUES (?, ?)", filmId, userId);
Запросы к БД в цикле.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DbFilmService.java
> +        List<Film> films = filmStorage.allFilms();
С базой данных так не работают. Представьте у вас в БД лежат несколько миллионов фильмов, я хочу выбрать 3 самых популярных. Вы выгружаете несколько миллионов ради трех. Фильтрацию необходимо делать на стороне БД. Чтобы БД выдала только то количество, которое нужно.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmGenreModifier.java
> +    private static final String COMEDY = "Комедия";
Эта информация уже есть в БД. Вы ее дублируете здесь. Эта информация может получаться из запроса к БД.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmMpaModifier.java
> +public class FilmMpaModifier {
Избыточный класс. Всю эту информацию можно получать запросами к БД.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public interface FilmService {
Необходимо добавить еще методов, которые сейчас идут из контроллера в обход сервиса сразу в storage.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/user/DbUserService.java
> +        return friends.stream().map(userStorage::getTargetUser)
Запросы к БД в цикле.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/user/DbUserService.java
> +                .map(userStorage::getTargetUser)
Запросы к БД в цикле.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +film_id integer,
Здесь должна быть связь на таблицу с фильмами.

2023-07-12 04:08 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +genre_id integer,
Здесь должна быть связь на таблицу с жанрами. И так далее по всему скрипту проверьте, имеются ли у вас необходимые связи, которые будут поддерживать БД в консистентном состоянии.

2023-07-13 00:21 UTC, KirillSenchenkov commented
Прошу прощения за бардак в коммитах и удаление пары файлов в ручную, очень не хотел шит чекстаил проходить.

2023-07-14 05:03 UTC, sergeymamonov approved these changes
Не устранено несоответствие IncorrectIdException и HttpStatus.NOT_FOUND. Название ошибки не соответствует ситуациям, когда она возникает. Она возникает, когда не найдены какие-то данные. То есть одна и та же ошибка кидается и когда нет какой-то сущности и когда встречаются невалидные данные.

2023-07-14 05:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/film/DbFilmService.java
> +                "ORDER BY COUNT(fl.USER_ID) DESC " +
Здесь в запросе указывается как упорядочить данные и ограничивается выводимое количество LIMIT ?.

А зачем еще после этого фильтровать полученные фильмы в строках 67 - 72?

2023-07-14 05:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/user/DbUserService.java
> +        String sql = "SELECT u.id, u.login, u.name, u.email, u.birthday, uf.friend_id FROM users u " +
Все проще
sqlQuery = "SELECT * FROM users u, friends f, friends o WHERE u.user_id = f.friend_id AND u.user_id = o.friend_id AND f.user_id = ? AND o.user_id = ?"

2023-07-14 05:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/user/DbUserService.java
> +        String sql = "SELECT u.id, u.login, u.name, u.email, u.birthday, uf.friend_id FROM users u " +
Подумайте, как упростить запрос

2023-07-15 10:59 UTC, merged